# Generated by Django 4.2.1 on 2024-01-03 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_group_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='heroe_id',
            new_name='hero_id',
        ),
    ]
