# Generated by Django 4.2.1 on 2024-01-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_heroe_id_hero_hero_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
